### ISSUE TITLE
Can ynh_install_ruby rely on rbenv debian package

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/Experimental_helpers#103]
From what I see in this script:
https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_install_ruby/ynh_install_ruby__2

Lots of logic are there to install rbenv.

However, this now packaged in bullseye:
```
$ sudo apt policy rbenv
rbenv:
  Installé : (aucun)
  Candidat : 1.1.2-1
 Table de version :
     1.1.2-1 500
        500 http://ftp.debian.org/debian bullseye/main amd64 Packages
```

What do you think of just relying on it? This would simplify a lot of things, I think, especially regarding the installation

**Comment by fflorent** [comment]
https://github.com/YunoHost-Apps/mastodon_ynh/blob/c3a3bff0d47833001fa6c1cf0b406a9c6e6ca589/scripts/ynh_install_ruby__2#L237-L241

These lines may imply that if we use the packaged version of rbenv, this will collide with the rbenv version installed using the existing helpers.

Hopefully, the existing helper is not used that much (8 packages): https://github.com/search?q=org%3AYunoHost-Apps+ynh_install_ruby__2&type=code

With the hypothesis we succeeded in making a new version of the helper with the debian version of rbenv, is it possible to require the `/etc/profile.d/rbenv` file to be absent? This would mean that we make a PR for all the repos in order to use the new helper in place of the existing ones and to cleanup what the helpers used to install.

I say `we`, but I would be glad to do it myself if you think that this could be nice this way.

**Comment by yalh76** [comment]
> 
> What do you think of just relying on it? This would simplify a lot of things, I think, especially regarding the installation

rbenv include in buster is 1.1.2 from march 2019 ..
https://github.com/rbenv/rbenv is from december 2022

so if we use rbenv included in buster, we will be limited to ruby version 2.7.1 and package using ynh_install_ruby__2, need ruby > 3.0

**Comment by fflorent** [comment]
Oh, the ruby versions being installable is coupled to the rbenv version, I didn't know that!

And versions > 3.0 are not even installable with bullseye.

Right, so let's close this issue, it is not relevant.
