### ISSUE TITLE
Warnings when using postgresql helpers

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/Experimental_helpers#13]
The invoked su commands with the user postgres produce multiple occurrences of this warning:
```
Warning: yunohost.hook <lambda> - [1158.1] could not change directory to "/tmp/yunohost_remove/scripts": Permission denied
```
It seems related to the fact that we are in this directory, and postgres user hasn't any right to be in there... Some additional parameter to pass to the [su command](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/postgres/postgres#L62) (multiple occurrences)...?

**Comment by Jibec** [comment]
I can try to fix this, last time I failed to understand the issue. Thanks for the hint, I'll try.
