### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kay0u** [YunoHost-Apps/Experimental_helpers#31]
Today on the support, someone have an error:

`/var/www/html/maintenance.keeweb.html: Aucun fichier ou dossier de ce type` at this line:

https://github.com/YunoHost-Apps/Experimental_helpers/blob/9fa989abeac2bf0382adc592a6902b66a7662de2/ynh_maintenance_mode/ynh_maintenance_mode#L31

In fact, the html folder didn't exist. I suggest to use something like: `mkdir -p /var/www/html/`right before `echo`

**Comment by maniackcrudelis** [comment]
Don't hesitate to commit into the helper
