### ISSUE TITLE
ynh_install_extra_repo and .asc key

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/Experimental_helpers#33]
ynh_install_extra_repo --key argument only allow gpg file.

It would be great that key argument accept .asc files

> "gpg --dearmor the-asc-file.asc" will convert from .asc to .gpg

**Comment by maniackcrudelis** [comment]
Hum ok, and in case the key is an asc, you can't load the key as it is ?
Which app is concerned ?

**Comment by yalh76** [comment]
If I provide the asc, the repository is not trusted.

it's for https://github.com/YunoHost-Apps/pleroma_ynh/tree/ynh_add_secure_repos__2
Here are the logs: https://paste.yunohost.org/upiracexof L387

**Comment by maniackcrudelis** [comment]
Ok I see the problem...
The script store the key under the name $app.gpg, whether it's a gpg key or an asc...

Well, I'll work on it.
Thanks for this bug report

**Comment by maniackcrudelis** [comment]
Done with https://github.com/YunoHost-Apps/Experimental_helpers/commit/218450f58f3220f8abba6d77d517bd362369bd08
Not tested, so tell me if it works as expected.

**Comment by yalh76** [comment]
Yes, it works as expected. A big thank you.
