### ISSUE TITLE
ynh_install_php : add possibility to install extra extensions

### ISSUE THREAD

**Issue by SimonMellerin** [YunoHost-Apps/Experimental_helpers#35]
This helper only install php and php-fpm, but other extensions are often need (like mysql, zip, curl...)

It could be great to add a list of extensions to install as a second argument

**Comment by maniackcrudelis** [comment]
If your app needs extensions, those extensions should be dependencies of your own app.
Use `ynh_install_app_dependencies` in your scripts to add those.
This helper has as a purpose only to install php itself.
