### ISSUE TITLE
ynh_add_secure_repos__2 generate error with package_check at remove step

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/Experimental_helpers#36]
To @maniackcrudelis 
When using ynh_add_secure_repos__2, package_check delete test fail:

![Capture](https://user-images.githubusercontent.com/30271971/55258888-71257c00-5264-11e9-8ab4-80e61f9c8f3b.PNG)

To check that, I generated the smallest package possible: https://github.com/yalh76/test_ynh , ynh_add_secure_repos__2 is only used during install

Tests done on the same fresh package_check installation

There are three branches:

- [with_ynh_add_secure_repos__2](https://github.com/yalh76/test_ynh/tree/with_ynh_add_secure_repos__2) - delete test fail - [complete logs](https://paste.yunohost.org/ogitihirur.go)
- [with_previous_ynh_add_secure_repos__2](https://github.com/yalh76/test_ynh/tree/with_previous_ynh_add_secure_repos__2) - delete test fail - [complete logs](https://paste.yunohost.org/ezowosemip.go)
- [without_ynh_add_secure_repos__2](https://github.com/yalh76/test_ynh/tree/without_ynh_add_secure_repos__2) - delete test is working - [complete logs](https://paste.yunohost.org/fewibocivi.py)

Delete test is also working with_ynh_add_secure_repos__2 when removing
https://github.com/YunoHost-Apps/Experimental_helpers/blob/ab1a0c1947357d641ba8e91696a747c9ebbdb7e3/ynh_add_secure_repos/ynh_add_secure_repos__2#L146

PS: the delete error only apply when using package_check, normal delete works

**Comment by maniackcrudelis** [comment]
But why would you not remove the repo during the remove script ?
And with `ynh_remove_extra_repo` it works ?

**Comment by yalh76** [comment]
I don't used `ynh_remove_extra_repo` to be sure the error didn't come from it. I first add the error on two packages with `ynh_remove_extra_repo` in the removce script

I will launch [another branch with ynh_remove_extra_repo](https://github.com/yalh76/test_ynh/tree/with_and_ynh_remove_extra_repo) just to be 100% sure and let you know the result

**Comment by yalh76** [comment]
Well... with ynh_remove_extra_repo in the remove script, it works.... remove test success
I completing misunderstanding. I will check with two two other packages....

**Comment by maniackcrudelis** [comment]
Apparently the error "Binary file (standard input) matches is not installed" would be related to grep. Can't see why or how though...

**Comment by yalh76** [comment]
Moving forward...

- One of the package use ynh_add_secure_repos__2, actually doing some tests
- The other one use ynh_install_php that use ynh_add_secure_repos__2: test done and remove test failing, so I create a new branch: https://github.com/yalh76/test_ynh/tree/with_ynh_install_php with only using `ynh_install_php` and `ynh_remove_php` and package_check delete test fail... [logs](https://paste.yunohost.org/zulesemizo.coffeescript)

**Comment by yalh76** [comment]
> 
> 
> Apparently the error "Binary file (standard input) matches is not installed" would be related to grep. Can't see why or how though...

Error only apply with package_check. standard remove with `yunohost app remove` works well
So difficult to handle...

**Comment by kay0u** [comment]
I have the same problem, I fixed it by adding a `> /dev/null` at the end of this line:

`wget -q "$key" -O - | gpg --dearmor | $wget_append /etc/apt/trusted.gpg.d/$name.$key_ext`

**Comment by yalh76** [comment]
> 
> 
> I have the same problem, I fixed it by adding a `> /dev/null` at the end of this line:
> 
> `wget -q "$key" -O - | gpg --dearmor | $wget_append /etc/apt/trusted.gpg.d/$name.$key_ext`

It tooks me 2 days to identify the bug and find a way to reproduce and test it ^^

**Comment by kay0u** [comment]
Tell me if it works for you, and if it does, I'll push this fix.

**Comment by maniackcrudelis** [comment]
Thanks @kay0u
I was about to do something like that, I saw that the key was into the log.

**Comment by yalh76** [comment]
I confirm, it solved the issue, tested on two packages

**Comment by kay0u** [comment]
Fix pushed, thank you for this report :-)
