### ISSUE TITLE
ynh_add_secure_repos__2 pinning and package version

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/Experimental_helpers#37]
Another one...

Sometime we need to add a repository with a newer version of a package than the one provided by official debian sources.

Example: 

- Elixir provided by debian stretch is 1.3.3-2 released in 2016 June. 
- When using ynh_install_extra_repo to add Elixir official repo, the repo is pinned 50. The last available version of Elixir is 1.8.1-1
- When installing Elixir with ynh_install_app_dependencies, it install the version 1.3.3-2 from debian official repository.

Is there a way to modify the pining when using ynh_install_extra_repo or a way to indicate which minimal version of a package we want when using ynh_install_app_dependencies ?

**Comment by maniackcrudelis** [comment]
Yep, you can specify the version you want by adding =version to the package name.
```
ynh_install_app_dependencies elixir=1.8.1-1
```
Just an example, this have to be the exact version number.

**Comment by yalh76** [comment]
Sadly, it doesn't seem that simple...

If I understand well [`ynh_install_app_dependencies`](https://github.com/YunoHost/yunohost/blob/8571ad874f9ad8b08b60e9503df4c798d31b7990/data/helpers.d/package#L206-L235)  :
- tooks the argument
- replaces space by comma space
- replaces pipe by space pipe space
- writes it in the .control file in the line `Depends:`

The content of the line `Depends:` is a [Debian relationship declaration field](https://www.debian.org/doc/debian-policy/ch-relationships.html)

So if I want Elixir 1.8.1-1 to be installed, I need `Depend: elixir (= 1.8.1-1)` in the .control file

But with ynh_install_app_dependencies and the space replacement by comma space there is no way to handle that....

Do you agree or my analysis is completely false ?

If you agree with me, it means that ynh_install_app_dependencies reduces the capacity to choose the version of a package. What would be a good way to restore the capacity to choose a package version ?

Maybe a solution: 

- Having an additional argument to `ynh_install_app_dependencies` : `--do-not-parse`
- When used, it directly write the dependencies argument in the Depends: Field

Example of use:

1. `ynh_install_app_dependencies elixir`
2. `ynh_install_app_dependencies elixir curl`
3. `ynh_install_app_dependencies "elixir (= 1.8.1-1), curl" --do-not-parse`
4. `ynh_install_app_dependencies "elixir (>= 1.8), curl" --do-not-parse`

Example 1 and 2 are usual use of `ynh_install_app_dependencies`, Example 3 and 4 to be able to choose package version.

**Comment by maniackcrudelis** [comment]
Yep you're right, I forgot that I myself encountered that error...
I gave you the apt install way to do it. But it doesn't work with equivs.

I don't think there's any easy way to do it for now.
So, I'm going to have a look to equivs and try to adapt the helper to manage correctly that.

**Comment by yalh76** [comment]
Thanks :)
If you need help for testing, I'm in ^^

**Comment by maniackcrudelis** [comment]
Finally, I changed the way extra repo were used, and especially I got rid of pinning, which is really a pain in the ass !

So now, pinning is at 995, so everything will be used in the extra repo.
But the extra repo is used only for a specific packages installation, and remove immediately after.

https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_add_secure_repos/ynh_add_secure_repos__3 is a the new version, with especially `ynh_install_extra_app_dependencies` which allow to install from an extra repository only the specified packages.
Also, I added `ynh_add_app_dependencies` to add dependencies to an app that has already use `ynh_install_app_dependencies` once. Dependencies will be added to the previous ones.

And https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_install_php/ynh_install_php__3 is the new version for php. It uses the new helper as explained above.

Tests are welcome ;)

**Comment by yalh76** [comment]
I will let you know :)

**Comment by yalh76** [comment]
`ynh_install_extra_app_dependencies` works very well, very cool

For ynh_install_php__3, something to notice: 
after using `ynh_install_php --phpversion="7.2"` the php repository is removed so the only way use it and be able to install php dependencies is to have something like: 

```bash
pkg_dependencies="postgresql etc..."
extra_pkg_dependencies="php7.2-pgsql etc..."
ynh_install_app_dependencies "$pkg_dependencies"
ynh_install_php --phpversion="7.2"
ynh_install_extra_app_dependencies --repo="https://packages.sury.org/php/ $(lsb_release -sc) main" --key="https://packages.sury.org/php/apt.gpg" --package="$extra_pkg_dependencies"
```

**Comment by maniackcrudelis** [comment]
Indeed, and that was expected.
But I agree that it would be easier to add an argument to ynh_install_php for installing extra php packages.

**Comment by yalh76** [comment]
Anyway, it works :) and that was more to have a sample of how to use it :)
