### ISSUE TITLE
not sure how to use php installer

### ISSUE THREAD

**Issue by Mrs-Feathers** [YunoHost-Apps/Experimental_helpers#51]
How do you use these helpers? i tried installing them as a plugin.. and running as a script [specifically the php installer one] and both attempts failed/errored. how can i use this to update my php?

**Comment by maniackcrudelis** [comment]
What exactly is your question ? How to use experimental helpers ? Or how to use ynh_install_php specifically ?

I feel like using experimental helpers is not clear to you.
So, to do so, you have to copy the code of the helper you want and integrate it into your _common.sh
So, it would be available for your scripts.

**Comment by decentral1se** [comment]
We need to add a README.md and and a "How to use them" section that says that you should simply copy the files into your scripts folder when you need to use them. Also, that we are using some sort of __2, ___3 convention for newer versions.

**Comment by yalh76** [comment]
You can check:
- https://github.com/YunoHost-Apps/drupal_ynh
or
- https://github.com/YunoHost-Apps/pixelfed_ynh

For the way how to use it
