### ISSUE TITLE
send_readme_to_admin bad syntax for diagnosis

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/Experimental_helpers#68]
Found by @SiM here: https://github.com/YunoHost-Apps/flarum_ynh/issues/147

> At the end of the flarum installation, there is an error regarding the yunohost diagnosis command (`yunohost tools diagnosis` instead of `yunohost diagnosis` 

Indeed, in YNH v3.8.4.9 the correct syntax is not:

```
root@vm:/media# yunohost tools diagnosis | grep -B 100 "services:" | sed '/services:/d'
usage: yunohost tools
                      {adminpw,maindomain,postinstall,update,upgrade,shell,shutdown,reboot,regen-conf,versions,migrations}
                      ...
                      [-h]
yunohost tools: error: invalid choice: 'diagnosis' (choose from 'adminpw', 'maindomain', 'postinstall', 'update', 'upgrade', 'shell', 'shutdown', 'reboot', 'regen-conf', 'versions', 'migrations')
```

The issue lies here : https://github.com/YunoHost-Apps/Experimental_helpers/blob/81584e68b4e148e704bb6f78aa63c315ed3edefd/send_readme_to_admin/send_readme_to_admin#L58

I have tried `yunohost diagnosis`, but then the `grep` has to be adapted, which is not within my capabilities. :)

**Comment by alexAubin** [comment]
Yes, personally I don't understand why this helper includes the diagnosis at the end ... The helper is meant to send a message about a specific app operation that just happened, like credentials or whatever ... I don't understand why it would send a bunch of info about the general health of the server ...

But yunohost 3.8 should automatically patch this helper on the fly when running app scripts, I don't know why it doesn't for flarum ...?
