### ISSUE TITLE
ynh_composer__2 shouldn't do a `composer update` but a `composer install`

### ISSUE THREAD

**Issue by SimonMellerin** [YunoHost-Apps/Experimental_helpers#72]
Hi,

ynh_composer__2 use `composer update` instead of `composer install`

`composer install` uses composer.lock file to install dependencies while `composer update` uses composer.json file. This can leads to a different set of packages and then introduce bugs.

`composer.lock` is a file which contains a version for each dependency. It lets app developers *freeze* dependencies version to be sure everyone will install the exact same set of packages.

Not sure if I'm clear or if I miss something, what do you think about this ?

**Comment by yalh76** [comment]
Can you provide the line from ynh_composer__2 or better from ynh_composer__3 => https://github.com/YunoHost-Apps/Experimental_helpers/pull/71/files

**Comment by SimonMellerin** [comment]
Ok my mistake I don't how I read the script, I suppose I'm a bit tired.. It already makes a `composer install`.... in ynh_composer__2 as in ynh_composer__3

Just to be sure I didn't open this issue for nothing, I will suggest to change the error message when `composer install` failed, I think my mistake come from there
